config/routes.rb
Rails.application.routes.draw do
  get 'bookings/rental'

  get 'bookings/booking'

  get 'bookings/listing'

  root 'bookings#listing'

  resources :rentals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental
  include ActiveModel::Model
  attr_accessor :name, :daily_rate

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def rental
  end

  def booking
  end

  def listing
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @rental = Rental.new
  end

  def create
    response = SyncApi::Client.create_rental({rental: { name: rental_params[:name], daily_rate: rental_params[:daily_rate] } })
    binding.pry
  end

  private

  def rental_params
    params.require(:rental).permit(:name, :daily_rate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/bookings/booking.html.erb
<%= form_for :booking,html:{ class: 'form-horizontal'} do |f| %>
	<div class="form-group">
      <label class="control-label col-sm-2">Name</label>
      <div class="col-sm-10">
      	<%= f.text_field :name, class: 'form-control', placeholder:'Enter Name' %>
      </div>
    </div>
    
    <div class="form-group">
      <label class="control-label col-sm-2">Daily Rate</label>
      <div class="col-sm-10">
        <%= f.number_field :daily_rate , class: 'form-control', placeholder:'Enter Daily Rate' %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2">Select Date</label>
      <div class="col-sm-4">
        <%= f.text_field :start_date , class: 'form-control', placeholder:'Select Start Date & Time' %>
      </div>
      <div class="col-sm-4">
        <%= f.text_field :end_date , class: 'form-control', placeholder:'Select End Date & Time' %>
      </div>
    </div>
    
    <div class="form-group">        
      <label class="control-label col-sm-2">Total Cost</label>
      <div class="col-sm-10">
        <%= f.text_field :total_cost, value: 0, class: 'form-control', disabled: true %>
      </div>
    </div>

    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
      	<%= f.submit "Submit", class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

<script>
$(function () {
  $('#booking_start_date').datetimepicker({
  	sideBySide: true
  });
  $('#booking_end_date').datetimepicker({
    sideBySide: true,
    useCurrent: false
  });
  $("#booking_start_date").on("dp.change", function (e) {
    $('#booking_end_date').data("DateTimePicker").minDate(e.date);
    calculate_total_cost();
  });
  $("#booking_end_date").on("dp.change", function (e) {
    $('#booking_start_date').data("DateTimePicker").maxDate(e.date);
    calculate_total_cost();
  });
  $("#booking_daily_rate").on("change",function(){
  	calculate_total_cost();
  });
});
function calculate_total_cost(){
	if($("#booking_start_date").val() && $("#booking_end_date").val() && $('#booking_daily_rate').val()){
		start_date = new Date($("#booking_start_date").val());
		end_date = new Date($("#booking_end_date").val());
		daily_rate = $('#booking_daily_rate').val();
		diff_date = (end_date - start_date)/ (1000 * 3600 * 24);
		$('#booking_total_cost').val(Math.round(diff_date) * daily_rate);
	}
}
</script>

app/views/bookings/listing.html.erb
<h2>LISTING</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>A</td>
      <td>10000</td>
    </tr>
    <tr>
      <td>B</td>
      <td>20000</td>
    </tr>
    <tr>
      <td>C</td>
      <td>30000</td>
    </tr>
  </tbody>
</table>

app/views/bookings/rental.html.erb
<%= form_for :rental,html:{ class: 'form-horizontal'} do |f| %>
	<div class="form-group">
      <label class="control-label col-sm-2">Name</label>
      <div class="col-sm-10">
      	<%= f.text_field :name, class: 'form-control', placeholder:'Enter Name' %>
      </div>
    </div>
    
    <div class="form-group">
      <label class="control-label col-sm-2">Daily Rate</label>
      <div class="col-sm-10">
        <%= f.number_field :daily_rate , class: 'form-control', placeholder:'Enter Daily Rate' %>
      </div>
    </div>
    
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
      	<%= f.submit "Submit", class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booking</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>	
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   	<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="<%= url_for root_path %>">Bookings</a>
		    </div>
		    <ul class="nav navbar-nav">
		      <li><a href="<%= url_for bookings_listing_path %>">Lisitng Page</a></li>
		      <li><a href="<%= url_for bookings_rental_path %>">Rental Page</a></li>
		      <li><a href="<%= url_for bookings_booking_path %>">Booking Page</a></li>
		    </ul>
		  </div>
		</nav>

	  <div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/rentals/new.html.erb
<%= form_for @rental, html:{ class: 'form-horizontal'} do |f| %>
	<div class="form-group">
      <label class="control-label col-sm-2">Name</label>
      <div class="col-sm-10">
      	<%= f.text_field :name, class: 'form-control', placeholder:'Enter Name' %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2">Daily Rate</label>
      <div class="col-sm-10">
        <%= f.number_field :daily_rate , class: 'form-control', placeholder:'Enter Daily Rate' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
      	<%= f.submit "Submit", class: 'btn btn-default' %>
      </div>
    </div>
<% end %>